import os
import re

strings_xml_path = "app/src/main/res/values/strings.xml"

def add_to_strings_xml(name, value):
    with open(strings_xml_path, "r", encoding="utf-8") as f:
        content = f.read()
    if f'<string name="{name}">' in content:
        return
    insert_idx = content.rfind("</resources>")
    if insert_idx != -1:
        new_content = content[:insert_idx] + f'    <string name="{name}">{value}</string>\n' + content[insert_idx:]
        with open(strings_xml_path, "w", encoding="utf-8") as f:
            f.write(new_content)

add_to_strings_xml("currency_yer", "ر.ي")
add_to_strings_xml("currency_sar", "ر.س")
add_to_strings_xml("currency_usd", "$")
add_to_strings_xml("currency_eur", "€")
add_to_strings_xml("currency_aed", "د.إ")
add_to_strings_xml("currency_name_yer", "ريال يمني")
add_to_strings_xml("currency_name_sar", "ريال سعودي")
add_to_strings_xml("currency_name_usd", "دولار أمريكي")
add_to_strings_xml("currency_name_eur", "يورو")
add_to_strings_xml("currency_name_aed", "درهم إماراتي")
add_to_strings_xml("source_system_dar", "دار")
add_to_strings_xml("source_system_habayeb", "حبايب")
add_to_strings_xml("category_flour", "دقيق")
add_to_strings_xml("category_sugar", "سكر")
add_to_strings_xml("category_rice", "أرز")
add_to_strings_xml("category_spices", "بهارات")
add_to_strings_xml("category_legumes", "بقوليات")
add_to_strings_xml("category_tea", "شاي")
add_to_strings_xml("category_vegetables", "خضار")
add_to_strings_xml("category_gas", "غاز")
add_to_strings_xml("category_electricity", "كهرباء")
add_to_strings_xml("category_water", "ماء")
add_to_strings_xml("category_internet", "إنترنت ورصيد")
add_to_strings_xml("category_milk", "حليب")
add_to_strings_xml("category_diapers", "حفاظات")
add_to_strings_xml("category_school", "مصروف مدرسي")
add_to_strings_xml("category_other", "أخرى")
add_to_strings_xml("category_savings", "ادخار")
add_to_strings_xml("category_emergency", "طوارئ")
add_to_strings_xml("category_medical", "علاج ودواء")
add_to_strings_xml("category_furniture", "أثاث ومستلزمات")
add_to_strings_xml("tab_food", "أغذية وتموين")
add_to_strings_xml("tab_bills", "فواتير وخدمات")
add_to_strings_xml("tab_family", "شؤون العائلة")
add_to_strings_xml("tab_savings", "ادخار وطوارئ")
add_to_strings_xml("default_unit_box", "كرتون")
add_to_strings_xml("default_unit_piece", "حبة")
add_to_strings_xml("backup_folder_name", "الدفتر الذكي")
add_to_strings_xml("customer_default_name", "عميل")
add_to_strings_xml("transaction_default_desc", "معاملة")
add_to_strings_xml("transaction_income", "وارد")
add_to_strings_xml("transaction_expense", "منصرف")
add_to_strings_xml("char_alef_hamza_above", "أ")
add_to_strings_xml("char_alef_hamza_below", "إ")
add_to_strings_xml("char_alef_madda", "آ")
add_to_strings_xml("char_taa_marboota", "ة")
add_to_strings_xml("char_alef_maksoura", "ى")
add_to_strings_xml("char_alef", "ا")
add_to_strings_xml("char_haa", "ه")
add_to_strings_xml("char_yaa", "ي")
add_to_strings_xml("filter_sort_largest", "الأكبر مبلغاً ▼")
add_to_strings_xml("filter_sort_smallest", "الأصغر مبلغاً ▲")
add_to_strings_xml("filter_sort_default", "الترتيب الافتراضي ⇅")
add_to_strings_xml("filter_sort_oldest", "الأقدم أولاً ⏱")
add_to_strings_xml("toast_reconnect_cloud", "يرجى إعادة ربط حساب السحاب لتجديد الصلاحية الأمنية 🔐")
add_to_strings_xml("desc_security", "الأمن والحماية")
add_to_strings_xml("desc_login", "الدخول")
add_to_strings_xml("desc_remove_logo", "حذف الشعار")
add_to_strings_xml("desc_deselect", "إلغاء التحديد")
add_to_strings_xml("desc_select_all", "تحديد الكل")
add_to_strings_xml("desc_delete_selected", "حذف المحدد")
add_to_strings_xml("text_selected_all", "تم تحديد الكل")
add_to_strings_xml("text_selected_count", "%1$d محدد")
add_to_strings_xml("export_backup_title", "تصدير ومشاركة الاحتياطي (WhatsApp / Drive)")
add_to_strings_xml("export_backup_chooser", "تصدير ومشاركة النسخة الاحتياطية")
add_to_strings_xml("export_backup_failed", "فشل تصدير الملف: %1$s")
add_to_strings_xml("forgot_password_link", "نسيت الرمز؟")
